### ISSUE TITLE
Feature request : adding titles to feeds

### ISSUE THREAD

**Issue by nylnook** [hurrymaplelad/docpad-plugin-rss#11]
Hi,

I bother you again... do you think adding titles to feeds would be possible with a syntax similar to this one ?

	default:
		collection: 'all_en'
		title: 'Every News'
		url: '/en-rss.xml'
	blog_en:
		collection: 'blog_en'
		title: 'Blog'
		url: '/blog-en-rss.xml

For example here : http://nylnook.com/en/follow/
all my feeds have the same title (nylnook), but not the same content...
It would be nice for the subscribers to have a correct title when subscribing ;)

Thanks a lot in advance !

**Comment by hurrymaplelad** [comment]
Sounds great!  Care to try a PR?  [This](https://github.com/hurrymaplelad/docpad-plugin-rss/blob/master/src/rss.plugin.coffee#L40) is the line you'd probably need to change.

**Comment by hurrymaplelad** [comment]
Fixed by #13
