### ISSUE TITLE
Grouping feeds in collection

### ISSUE THREAD

**Issue by nylnook** [hurrymaplelad/docpad-plugin-rss#7]
Hi,

I try to group two path in one collection
```
all_en: ->
   @getCollection("html").findAllLive($or: [{relativeOutDirPath:'en/img'}, {relativeOutDirPath:'en/blog'}],[{date:-1}])
```
But I only get the second path in collection on rendering
Here is a result : http://nylnook.com/en-rss.xml (only blog post render)
No errors nor warning in console.

My code is here for testing purposes : https://github.com/nylnook/nylnook-website

First, I reported this in the Docpad issue tracker :
https://github.com/docpad/docpad/issues/882

But it seem scoped to this plugin because grouping work in other contexts.

Any idea ?

**Comment by nylnook** [comment]
More than one year later, still interested... ! Thanks

**Comment by hurrymaplelad** [comment]
Hi @nylnook!  I tried cloning your code, but it's HUGE (several hundred megabytes before I stopped).  A smaller code sample reproducing your issue would make it much easier to troubleshoot.

I added a [test case](https://github.com/hurrymaplelad/docpad-plugin-rss/blob/master/src/rss.tester.coffee#L37) covering the setup you describe and it [seems to work](https://github.com/hurrymaplelad/docpad-plugin-rss/blob/master/test/out-expected/rss-folders.xml).

**Comment by nylnook** [comment]
hi @hurrymaplelad !
Thanks for you work... I'm sorry with the huge repo, but it's the game when you do pictures as a living ;)
I tested again with your syntax style and it didn't worked... but then I updated my docpad install and your plugin, tried again... and now it work !
nylnook/nylnook-website@92547dd5397ee2a0a62fc62613f34e43e3f2e190
So I'm really sorry I didn't updated before bothering you... My apologies... !

**Comment by hurrymaplelad** [comment]
Glad it worked out!
